"""Tina: OCR text-layer remediation for scanned (image-only) PDF pages.

Adds an invisible, positioned text layer — generated by the local tesseract
engine — to pages that are a single full-page image with no extractable text.
The scan image itself is never altered (the overlay draws with text rendering
mode 3, invisible), pages that already carry text are left untouched, and the
tool declines honestly when there is nothing it can OCR with confidence.

The recognized text is machine-generated: recognition errors are likely and a
human must review it. Applying it resolves the technical no-text-layer finding
only; it makes no accessibility or conformance claim of any kind.
"""
from __future__ import annotations

import io
import subprocess
from hashlib import sha256
from typing import Any, Callable

from PIL import Image
from pypdf import PdfReader, PdfWriter
from pypdf.generic import ArrayObject, DictionaryObject, NameObject, StreamObject

from tina.kernel import ToolGateway, ToolManifest
from tina.remedy import RemediationError

REMEDIATE_OCR_PERMISSION = "document.remediate.ocr"
CONFIDENCE_FLOOR = 40.0
TESSERACT_TIMEOUT_SECONDS = 120

TesseractRunner = Callable[[bytes], str]

MISSING_ENGINE_MESSAGE = (
    "The OCR engine (tesseract) is not installed on this computer, so no text "
    "layer was applied. Install tesseract (for example: apt install "
    "tesseract-ocr) and re-run, or rebuild the document as an accessible HTML "
    "working copy instead."
)

ENGINE_TIMEOUT_MESSAGE = (
    "The OCR engine (tesseract) timed out on a page image, so no text layer "
    "was applied. Try again on a smaller document, or rebuild the document as "
    "an accessible HTML working copy instead."
)

HUMAN_REVIEW_NOTE = (
    "The applied text layer is machine-generated OCR output. Recognition "
    "errors are likely; a human must review the recognized text against the "
    "scanned page images before relying on it."
)


def run_tesseract_tsv(image_bytes: bytes) -> str:
    """Default engine runner: feed raw image bytes to tesseract, return TSV text.

    Raises FileNotFoundError when the binary is absent (translated to a
    RemediationError by the tool handler) and RemediationError when the engine
    runs but cannot read the image.
    """
    result = subprocess.run(
        ["tesseract", "stdin", "stdout", "tsv"],
        input=image_bytes,
        capture_output=True,
        timeout=TESSERACT_TIMEOUT_SECONDS,
        check=False,
    )
    if result.returncode != 0:
        stderr = result.stderr.decode("utf-8", errors="replace").strip()[:500]
        raise RemediationError(
            "The OCR engine could not read a page image "
            f"(tesseract exit {result.returncode}: {stderr or 'no detail'}). "
            "Rebuild the document as an accessible HTML working copy instead."
        )
    return result.stdout.decode("utf-8", errors="replace")


def parse_tsv_words(tsv_text: str) -> list[dict[str, Any]]:
    """Parse tesseract TSV output into word rows (level 5) with pixel boxes."""
    words: list[dict[str, Any]] = []
    for row in tsv_text.splitlines()[1:]:
        cols = row.split("\t")
        if len(cols) != 12 or cols[0] != "5":
            continue
        try:
            conf = float(cols[10])
            left, top, width, height = (int(cols[6]), int(cols[7]), int(cols[8]), int(cols[9]))
        except ValueError:
            continue
        text = cols[11].strip()
        if not text:
            continue
        words.append({"left": left, "top": top, "width": width, "height": height,
                      "conf": conf, "text": text})
    return words


def _pdf_escape_latin1(text: str) -> bytes:
    """Escape a word for a PDF literal string; caller ensures latin-1 encodability."""
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)").encode("latin-1")


def build_overlay_stream(words: list[dict[str, Any]], img_w: int, img_h: int,
                         box_w: float, box_h: float) -> bytes:
    """Invisible-text content stream mapping pixel word boxes onto the page.

    The scan image fills the MediaBox, so scale = box / pixel dimensions, and
    the y axis flips (PDF origin is bottom-left; the word baseline sits at the
    bottom of the recognized box).
    """
    sx, sy = box_w / img_w, box_h / img_h
    parts = [b"q", b"BT", b"3 Tr"]  # 3 Tr = invisible text rendering mode
    for word in words:
        x = word["left"] * sx
        y = box_h - (word["top"] + word["height"]) * sy
        size = max(word["height"] * sy, 1.0)
        parts.append(b"/FOCR %.2f Tf" % size)
        parts.append(b"1 0 0 1 %.2f %.2f Tm" % (x, y))
        parts.append(b"(" + _pdf_escape_latin1(word["text"]) + b") Tj")
    parts += [b"ET", b"Q"]
    return b"\n".join(parts)


def _page_eligibility(page: Any) -> tuple[bool, str]:
    """Decide whether a page is the scan case this tool handles."""
    if (page.extract_text() or "").strip():
        return False, "page already has extractable text"
    if page.get("/Rotate", 0):
        return False, "page is rotated; coordinate mapping is not supported"
    if page.get("/Contents") is None:
        return False, "page has no content stream drawing the scan image"
    box = page.mediabox
    if float(box.left) != 0.0 or float(box.bottom) != 0.0:
        return False, "page MediaBox origin is not (0, 0)"
    if float(box.width) <= 0.0 or float(box.height) <= 0.0:
        return False, "page MediaBox has no positive area"
    try:
        image_count = len(list(page.images))
    except Exception:
        return False, "page images could not be enumerated"
    if image_count == 0:
        return False, "page has no image to OCR"
    if image_count > 1:
        return False, "page is composed of multiple images"
    return True, "eligible"


def _attach_overlay(writer: PdfWriter, page: Any, content: bytes) -> None:
    overlay = StreamObject()
    overlay.set_data(content)
    overlay_ref = writer._add_object(overlay)

    existing = page.raw_get("/Contents")
    resolved = existing.get_object()
    if isinstance(resolved, ArrayObject):
        contents = ArrayObject(list(resolved) + [overlay_ref])
    else:
        contents = ArrayObject([existing, overlay_ref])
    page[NameObject("/Contents")] = contents

    resources = page.get("/Resources")
    resources = resources.get_object() if resources is not None else None
    if resources is None:
        resources = DictionaryObject()
        page[NameObject("/Resources")] = resources
    fonts = resources.get("/Font")
    fonts = fonts.get_object() if fonts is not None else None
    if fonts is None:
        fonts = DictionaryObject()
        resources[NameObject("/Font")] = fonts
    font = DictionaryObject({
        NameObject("/Type"): NameObject("/Font"),
        NameObject("/Subtype"): NameObject("/Type1"),
        NameObject("/BaseFont"): NameObject("/Helvetica"),
    })
    fonts[NameObject("/FOCR")] = writer._add_object(font)


def _verify_untouched_pages(payload: bytes, remediated: bytes,
                            ocred_indexes: set[int]) -> None:
    """Anti-vandal check: pages we did not OCR must behave identically."""
    before = PdfReader(io.BytesIO(payload), strict=False)
    after = PdfReader(io.BytesIO(remediated), strict=False)
    if len(before.pages) != len(after.pages):
        raise RemediationError(
            "Verification failed: the page count changed during OCR remediation; the result was discarded."
        )
    for index, (page_before, page_after) in enumerate(zip(before.pages, after.pages)):
        if len(list(page_before.images)) != len(list(page_after.images)):
            raise RemediationError(
                f"Verification failed: page {index + 1}'s image content changed during OCR remediation; the result was discarded."
            )
        if index in ocred_indexes:
            continue
        if (page_before.extract_text() or "") != (page_after.extract_text() or ""):
            raise RemediationError(
                f"Verification failed: page {index + 1} was not eligible for OCR but its text changed; the result was discarded."
            )


def _apply_text_layer(input_data: dict[str, Any], runner: TesseractRunner) -> dict[str, Any]:
    payload: bytes = input_data["payload"]

    try:
        reader = PdfReader(io.BytesIO(payload), strict=False)
    except Exception as error:
        raise RemediationError(f"The PDF could not be parsed for remediation: {type(error).__name__}") from error
    if reader.is_encrypted:
        raise RemediationError("Encrypted PDFs are not remediated; request an unencrypted source copy.")

    writer = PdfWriter(clone_from=reader)

    eligible: list[int] = []
    skipped: list[dict[str, Any]] = []
    for index, page in enumerate(writer.pages):
        ok, reason = _page_eligibility(page)
        if ok:
            eligible.append(index)
        else:
            skipped.append({"page": index + 1, "reason": reason})

    if not eligible:
        raise RemediationError(
            "There are no scanned pages found to OCR: every page either already "
            "has a text layer or is not a single full-page scan image. If the "
            "document still reads poorly, rebuild it as an accessible HTML "
            "working copy instead."
        )

    ocred_indexes: set[int] = set()
    words_applied = 0
    confidences: list[float] = []
    dropped_non_encodable = 0

    for index in eligible:
        page = writer.pages[index]
        image = list(page.images)[0]
        try:
            pixel_width, pixel_height = Image.open(io.BytesIO(image.data)).size
        except Exception:
            skipped.append({"page": index + 1, "reason": "scan image could not be decoded"})
            continue
        if pixel_width <= 0 or pixel_height <= 0:
            skipped.append({"page": index + 1, "reason": "scan image could not be decoded"})
            continue
        try:
            tsv_text = runner(image.data)
        except FileNotFoundError as error:
            raise RemediationError(MISSING_ENGINE_MESSAGE) from error
        except subprocess.TimeoutExpired as error:
            raise RemediationError(ENGINE_TIMEOUT_MESSAGE) from error

        kept: list[dict[str, Any]] = []
        for word in parse_tsv_words(tsv_text):
            if word["conf"] < CONFIDENCE_FLOOR:
                continue
            try:
                word["text"].encode("latin-1")
            except UnicodeEncodeError:
                dropped_non_encodable += 1
                continue
            kept.append(word)
        if not kept:
            skipped.append({"page": index + 1, "reason": "no OCR words met the confidence floor"})
            continue

        box = page.mediabox
        content = build_overlay_stream(kept, pixel_width, pixel_height,
                                       float(box.width), float(box.height))
        _attach_overlay(writer, page, content)
        ocred_indexes.add(index)
        words_applied += len(kept)
        confidences.extend(word["conf"] for word in kept)

    if not ocred_indexes:
        raise RemediationError(
            "OCR produced no legible text on the scanned page(s), so no text "
            "layer was applied. Route the document for human transcription or "
            "rebuild it as an accessible HTML working copy instead."
        )

    output = io.BytesIO()
    writer.write(output)
    remediated = output.getvalue()

    _verify_untouched_pages(payload, remediated, ocred_indexes)

    action = {
        "rule_id": "PDF.TEXT_LAYER",
        "action": "apply_ocr_text_layer",
        "provenance": "ocr_generated",
        "pages_ocred": len(ocred_indexes),
        "pages_skipped": skipped,
        "words_applied": words_applied,
        "words_dropped_non_encodable": dropped_non_encodable,
        "mean_confidence": round(sum(confidences) / len(confidences), 1),
        "confidence_floor": CONFIDENCE_FLOOR,
        "note": HUMAN_REVIEW_NOTE,
        "detail": (
            "Appended an invisible (text rendering mode 3), positionally mapped "
            "text layer generated by tesseract to each single-image page that "
            "had no extractable text. Scan images were not modified; pages "
            "with existing text were left untouched."
        ),
    }
    return {
        "actions": [action],
        "source_sha256": f"sha256:{sha256(payload).hexdigest()}",
        "remediated_sha256": f"sha256:{sha256(remediated).hexdigest()}",
        "source_bytes": len(payload),
        "remediated_bytes": len(remediated),
        "remediated_payload": remediated,
    }


class OcrRemediation:
    """Adds a machine-generated OCR text layer to scanned pages of a PDF copy."""

    CONTRACT_VERSION = "tina-remediation-report/v1"
    CLAIM_BOUNDARY = (
        "An OCR text layer makes the words on scanned pages machine-readable. "
        "The text is machine-generated: recognition errors are likely, and a "
        "human must review it against the page images. This resolves the "
        "technical no-text-layer finding only; no conformance is implied."
    )

    def __init__(self, gateway: ToolGateway) -> None:
        self.gateway = gateway

    @classmethod
    def with_builtin_tools(cls, tesseract_runner: TesseractRunner | None = None) -> "OcrRemediation":
        runner = tesseract_runner or run_tesseract_tsv
        gateway = ToolGateway()
        gateway.register(
            ToolManifest(
                name="apply_text_layer",
                version="1.0.0",
                purpose="Add an invisible, positioned OCR text layer to scanned pages of a PDF copy.",
                deterministic=False,  # output depends on the installed OCR engine build
                mutates_document=True,
                permissions=(REMEDIATE_OCR_PERMISSION,),
                timeout_ms=TESSERACT_TIMEOUT_SECONDS * 1_000,
            ),
            lambda input_data: _apply_text_layer(input_data, runner),
        )
        return cls(gateway)

    def apply(self, filename: str, payload: bytes) -> tuple[bytes, dict[str, Any]]:
        """OCR eligible scanned pages of an in-memory copy; return (new bytes, report)."""
        execution = self.gateway.execute(
            "apply_text_layer",
            {"payload": payload},
            {REMEDIATE_OCR_PERMISSION},
        )
        remediated: bytes = execution["output"].pop("remediated_payload")
        report = {
            "contract_version": self.CONTRACT_VERSION,
            "claim_boundary": self.CLAIM_BOUNDARY,
            "filename": filename,
            "tool": execution["tool"],
            "tool_version": execution["tool_version"],
            "deterministic": execution["deterministic"],
            "mutates_document": execution["mutates_document"],
            **execution["output"],
        }
        return remediated, report
